# Additional API information which are used in various API specifications
# The title of the application
info_title: "Fusio"
# A short description of the application. CommonMark syntax MAY be used for rich 
# text representation
info_description: ""
# A URL to the Terms of Service for the API. MUST be in the format of a URL
info_tos: ""
# The identifying name of the contact person/organization
info_contact_name: ""
# The URL pointing to the contact information. MUST be in the format of a URL
info_contact_url: ""
# The email address of the contact person/organization. MUST be in the format of 
# an email address
info_contact_email: ""
# The license name used for the API
info_license_name: ""
# A URL to the license used for the API. MUST be in the format of a URL
info_license_url: ""

# Subject of the password reset mail
mail_pw_reset_subject: "Fusio password reset"
# Body of the password reset mail
mail_pw_reset_body: "Hello {name},

you have requested to reset your password.
To set a new password please visit the following link:
${env.FUSIO_URL}\/developer\/password\/confirm\/{token}

Please ignore this email if you have not requested a password reset.
"

# Subject of the activation mail
mail_register_subject: "Fusio registration"
# Body of the activation mail
mail_register_body: "Hello {name},

you have successful registered at Fusio.
To activate you account please visit the following url:
${env.FUSIO_URL}\/developer\/register\/activate\/{token}
"
