name: CI
on:
  pull_request:
  push:
  schedule:
    - cron: '0 0 * * 0'
jobs:
  psalm:
    name: Psalm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          coverage: none
      - name: Composer install
        run: composer install --no-interaction --no-ansi --no-progress
      - name: Run Psalm
        run: vendor/bin/psalm --no-progress --show-info=false
  phpunit:
    name: "PHPUnit (PHP: ${{ matrix.php-versions }})"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions:
          - 8.1
          - 8.2
        connection:
          - 'pdo-mysql://root:test1234@localhost/fusio'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none
      - name: Setup MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e "CREATE DATABASE fusio;" -uroot -proot
          mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'test1234';" -uroot -proot
      - name: Composer install
        run: composer install --no-interaction --no-ansi --no-progress
      - name: Wait for
        env:
          APP_CONNECTION: ${{ matrix.connection }}
        run: php bin/fusio system:wait_for
      - name: Run PHPUnit
        env:
          APP_CONNECTION: ${{ matrix.connection }}
        run: vendor/bin/phpunit
